name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alanx30/ecommercemodulo_apinode:${{ github.sha }}
    - name: push the Docker image
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }} && docker push alanx30/ecommercemodulo_apinode:${{ github.sha }}

# Set up the Kubernetes CLI with your DigitalOcean Kubernetes cluster.
    - uses: actions/checkout@v2
    - name: Deploy to cluster
      uses: myrotvorets/kubectl-action@2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: latest
        args: set image --record deployment/application container=${{ github.repository }}:${{ github.sha }}
    - name: Verify deployment
      uses: myrotvorets/kubectl-action@2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: latest
        args: rollout status deployment/application